
//Common Actions
export const SHOW_MSG = 'SHOW_MSG';  //全局显示消息
export const HIDE_MSG = 'HIDE_MSG';  //全局隐藏消息

//Login
export const GET_USERINFO = "GET_USERINFO";
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const LOGGED_IN = "LOGGED_IN";


//Menu Actions
export const CHANGE_MENU_ROUTE = "CHANGE_MENU_ROUTE";
export const CHOOSED_TREE_LEAVES = "CHOOSED_TREE_LEAVES";

//Dropdown
export const RECEIVED_DROPDOWN_DATA = "RECEIVED_DROPDOWN_DATA";
export const RECEIVED_DROPDOWN_CANTSELECT_DATA = "RECEIVED_DROPDOWN_CANTSELECT_DATA";

//Book Actions
export const RECEIVE_BOOK_DATA = "RECEIVE_BOOK_DATA";
export const RECEIVE_ARTICLE_INFO_DATA = "RECEIVE_ARTICLE_INFO_DATA";
export const RECEIVE_MENU_INFO_DATA = "RECEIVE_MENU_INFO_DATA";
export const RECEIVE_FASHION_INFO_DATA = "RECEIVE_FASHION_INFO_DATA";

//Article Actions
export const RECEIVE_ARTICLE_DATA = "RECEIVE_ARTICLE_DATA";
export const RECEIVE_ACCOUNT_DATA = "RECEIVE_ACCOUNT_DATA";
export const RECEIVE_RESOURCE_DATA = "RECEIVE_RESOURCE_DATA";
export const RECEIVE_TAGS_ARR_DATA = "RECEIVE_TAGS_ARR_DATA";

//CrowdFunding Actions
export const RECEIVE_CROWDFUNDING_LIST = "RECEIVE_CROWDFUNDING_LIST";
export const RECEIVE_CROWDFUNDING_DETAIL = "RECEIVE_CROWDFUNDING_DETAIL";