//Menu Actions
export const CHANGE_MENU_ROUTE = "CHANGE_MENU_ROUTE";
export const CHOOSED_TREE_LEAVES = "CHOOSED_TREE_LEAVES";

//Dropdown
export const RECEIVED_DROPDOWN_DATA = "RECEIVED_DROPDOWN_DATA";
export const RECEIVED_DROPDOWN_CANTSELECT_DATA = "RECEIVED_DROPDOWN_CANTSELECT_DATA";

//Book Actions
export const RECEIVE_BOOK_DATA = "RECEIVE_BOOK_DATA";

//Login
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const LOGGED_IN = "LOGGED_IN";

